import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

// Register fonts if needed
Font.register({
  family: 'Helvetica',
  fonts: [
    { src: 'https://fonts.gstatic.com/s/helvetica-neue/v23/1Ptsg8zYS_SKggPNyC0IT4tt.ttf' }
  ]
});

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#CCCCCC',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 3,
  },
  filterSection: {
    marginBottom: 20,
    padding: 10,
    backgroundColor: '#F9FAFB',
    borderRadius: 4,
  },
  filterRow: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  filterLabel: {
    width: 100,
    fontSize: 10,
    color: '#6B7280',
    fontWeight: 'bold',
  },
  filterValue: {
    flex: 1,
    fontSize: 10,
    color: '#1F2937',
  },
  summarySection: {
    marginBottom: 20,
    padding: 10,
    backgroundColor: '#EFF6FF',
    borderRadius: 4,
  },
  summaryTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  summaryLabel: {
    fontSize: 10,
    color: '#4B5563',
  },
  summaryValue: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  table: {
    marginTop: 20,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#D1D5DB',
  },
  tableHeaderCell: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#4B5563',
    flex: 1,
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E7EB',
  },
  tableCell: {
    fontSize: 8,
    color: '#1F2937',
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    fontSize: 8,
    color: '#9CA3AF',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
  statusBadge: {
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 2,
    fontSize: 6,
    fontWeight: 'bold',
    textAlign: 'center',
    width: 50,
  },
  pendingBadge: {
    backgroundColor: '#FEF3C7',
    color: '#92400E',
  },
  approvedBadge: {
    backgroundColor: '#DBEAFE',
    color: '#1E40AF',
  },
  rejectedBadge: {
    backgroundColor: '#FEE2E2',
    color: '#991B1B',
  },
  fulfilledBadge: {
    backgroundColor: '#D1FAE5',
    color: '#065F46',
  },
});

interface StockRequestsReportPDFProps {
  requests: any[];
  summary: {
    totalRequests: number;
    totalQuantity: number;
    pendingCount: number;
    approvedCount: number;
    rejectedCount: number;
    fulfilledCount: number;
  };
  dateRange: { from: string; to: string };
  status: string;
  direction: string;
  fromZone: string;
  toZone: string;
  product: string;
  generatedBy: string;
}

const StockRequestsReportPDF: React.FC<StockRequestsReportPDFProps> = ({
  requests,
  summary,
  dateRange,
  status,
  direction,
  fromZone,
  toZone,
  product,
  generatedBy,
}) => {
  const getStatusStyle = (status: string) => {
    switch (status.toLowerCase()) {
      case 'pending': return styles.pendingBadge;
      case 'approved': return styles.approvedBadge;
      case 'rejected': return styles.rejectedBadge;
      case 'fulfilled': return styles.fulfilledBadge;
      default: return {};
    }
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Stock Requests Report</Text>
          <Text style={styles.subtitle}>Generated on: {new Date().toLocaleString()}</Text>
          <Text style={styles.subtitle}>Generated by: {generatedBy}</Text>
        </View>

        {/* Filters */}
        <View style={styles.filterSection}>
          <Text style={[styles.summaryTitle, { marginBottom: 5 }]}>Applied Filters</Text>
          <View style={styles.filterRow}>
            <Text style={styles.filterLabel}>Status:</Text>
            <Text style={styles.filterValue}>{status}</Text>
          </View>
          <View style={styles.filterRow}>
            <Text style={styles.filterLabel}>Date Range:</Text>
            <Text style={styles.filterValue}>{dateRange.from || 'Any'} to {dateRange.to || 'Any'}</Text>
          </View>
          <View style={styles.filterRow}>
            <Text style={styles.filterLabel}>Direction:</Text>
            <Text style={styles.filterValue}>{direction}</Text>
          </View>
          <View style={styles.filterRow}>
            <Text style={styles.filterLabel}>From Zone:</Text>
            <Text style={styles.filterValue}>{fromZone}</Text>
          </View>
          <View style={styles.filterRow}>
            <Text style={styles.filterLabel}>To Zone:</Text>
            <Text style={styles.filterValue}>{toZone}</Text>
          </View>
          <View style={styles.filterRow}>
            <Text style={styles.filterLabel}>Product:</Text>
            <Text style={styles.filterValue}>{product}</Text>
          </View>
        </View>

        {/* Summary Statistics */}
        <View style={styles.summarySection}>
          <Text style={styles.summaryTitle}>Summary Statistics</Text>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Total Requests:</Text>
            <Text style={styles.summaryValue}>{summary.totalRequests}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Total Quantity:</Text>
            <Text style={styles.summaryValue}>{summary.totalQuantity}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Pending:</Text>
            <Text style={styles.summaryValue}>{summary.pendingCount}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Approved:</Text>
            <Text style={styles.summaryValue}>{summary.approvedCount}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Rejected:</Text>
            <Text style={styles.summaryValue}>{summary.rejectedCount}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Fulfilled:</Text>
            <Text style={styles.summaryValue}>{summary.fulfilledCount}</Text>
          </View>
        </View>

        {/* Table */}
        <View style={styles.table}>
          {/* Table Header */}
          <View style={styles.tableHeader}>
            <Text style={[styles.tableHeaderCell, { flex: 1.5 }]}>Request ID</Text>
            <Text style={[styles.tableHeaderCell, { flex: 1 }]}>Status</Text>
            <Text style={[styles.tableHeaderCell, { flex: 1.5 }]}>From Zone</Text>
            <Text style={[styles.tableHeaderCell, { flex: 1.5 }]}>To Zone</Text>
            <Text style={[styles.tableHeaderCell, { flex: 2 }]}>Products</Text>
            <Text style={[styles.tableHeaderCell, { flex: 0.8 }]}>Qty</Text>
            <Text style={[styles.tableHeaderCell, { flex: 1.5 }]}>Requested By</Text>
            <Text style={[styles.tableHeaderCell, { flex: 1 }]}>Date</Text>
          </View>

          {/* Table Rows */}
          {requests.map((request, index) => (
            <View key={index} style={styles.tableRow}>
              <Text style={[styles.tableCell, { flex: 1.5 }]}>{request['Request ID']}</Text>
              <View style={[styles.tableCell, { flex: 1 }]}>
                <Text style={[styles.statusBadge, getStatusStyle(request.Status)]}>
                  {request.Status}
                </Text>
              </View>
              <Text style={[styles.tableCell, { flex: 1.5 }]}>{request['From Zone']}</Text>
              <Text style={[styles.tableCell, { flex: 1.5 }]}>{request['To Zone']}</Text>
              <Text style={[styles.tableCell, { flex: 2 }]}>{request['Products']}</Text>
              <Text style={[styles.tableCell, { flex: 0.8 }]}>{request['Total Quantity']}</Text>
              <Text style={[styles.tableCell, { flex: 1.5 }]}>{request['Requested By']}</Text>
              <Text style={[styles.tableCell, { flex: 1 }]}>{request['Request Date']}</Text>
            </View>
          ))}
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          This is a computer generated report. Page 1 of 1
        </Text>
      </Page>
    </Document>
  );
};

export default StockRequestsReportPDF;